# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'RedBeatMachine' do
pod 'Firebase', '>= 2.5.1'
end

target 'RedBeatMachineTests' do

end

target 'RedBeatMachineUITests' do

end

